import { StyleSheet } from "react-native";

export const StyleLogin = StyleSheet.create({
    Container_1:{
        width:'100%',
        justifyContent:'flex-end',
        alignItems:'center',
        height:100
    },
    Logo_Container_1:{
        height:40,
        width:40,
        objectFit:'contain',        
    },
    ContainerTextInputPassword:{
        borderWidth:1,
        height:60,
        borderRadius:10,
        flexDirection:'row',
        justifyContent:'space-between',
        borderColor:'#dee2e6',
        paddingHorizontal:5,
        backgroundColor:'white'
    },
    TextEmail:{
        borderWidth:1,
        height:60,
        borderRadius:10,
        fontSize:18,
        color:'gray',
        borderColor:'#dee2e6',
        paddingHorizontal:5 ,
        backgroundColor:'white'       
    }
    ,
    TextInputPassword:{
        fontSize:18,
        color:'gray',
        width:'80%',
        height:'100%',
        justifyContent:'center'
    },
    BtnShowPassword:{
        height:'100%',justifyContent:'center'
    },
    ContainerCheckBox:{
        flexDirection:'row',
        alignItems:'center',
        gap:5,
        padding:5
    },
    BtnLogin:{
        width:'100%',
        paddingVertical:10,
        borderWidth:1,
        borderRadius:30,
        backgroundColor:'black'       
    },
    TextBtnLogin:{
        textAlign:'center',
        fontSize:20,
        color:'white',
        fontWeight:'500',       
    },
    TextOtherForm:{
        textAlign:'center',
        fontWeight:'400',
        color:'gray'
    },
    ContainerBtnInicioRapido:{
        flexDirection:'row',
        alignItems:'center',
        justifyContent:'space-between',
        paddingVertical:20
    },
    BtnFacebook:{
        height:70,
        width:70,
        padding:10,
        borderWidth:1,
        borderRadius:10,
        overflow:'hidden',
        justifyContent:'center',
        alignItems:'center',
        borderColor:'#dee2e6',
        backgroundColor:'white'
    },
    BtnGoogle:{
        padding:10,
        borderWidth:1,
        borderRadius:10,
        borderColor:'#dee2e6',
        backgroundColor:'white'
    },
    BtnApple:{
        padding:10,
        borderWidth:1,
        borderRadius:10,
        borderColor:'#dee2e6',
        backgroundColor:'white'
    },
    TextDontHaveAccount:{
        width:'100%',
        alignItems:'center',
        justifyContent:'center',
        flexDirection:'row',
        gap:5
    },
    ContainerInicios:{
        paddingHorizontal:20,
        paddingVertical:20,
        gap:10
    }
});